#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:00:00
#SBATCH --output=outputs/install_env_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/vlm-compositionality/
# conda env create -f environment.yml
source activate cogvlm
# pip uninstall -y open_flamingo
pip uninstall -y torch
pip install deepspeed==0.13.5
