#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Sugarcrepe-CogVLM
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=10:00:00
#SBATCH --output=outputs/runs/sugarcrepe_cogvlm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/vlm-compositionality/

source activate fomo-vlm-comp

pip install easydict gdown spacy
pip install accelerate
pip install -i https://pypi.org/simple/ bitsandbytes
srun python -m spacy download en_core_web_sm

srun python main_generative_benchmarks.py --model_list THUDM/cogvlm-chat-hf --benchmark_list sugarcrepe --prompt_type_list gpt4-shorterprompt --evaluation_type accuracy_score
