#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=RunInference
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd $HOME/vlm-compositionality/

source activate fomo-vlm-comp
# srun python -m spacy download en_core_web_sm

srun python main_benchmarks.py --model_list ViT-L-14 ViT-L-14-quickgelu ViT-H-14 coca_ViT-B-32  --pretrained_list openai metaclip_400m laion2b_s32b_b79k laion2b_s13b_b90k 